trigger:
- staging

jobs:
  - job: Tests

    pool:
      name: 'Default'

    workspace:
      clean: resources

    steps:

    - powershell: echo "IP for RDP connections:" $(Invoke-RestMethod ipinfo.io/ip)
      displayName: 'Get RDP address'

    - powershell: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      displayName: 'Setup Screen Resolution'

    - script: yarn install --frozen-lockfile --check-files
      displayName: 'Install Dependencies'

    - script: 'yarn lint'
      displayName: 'TSLint'

    - script: 'yarn compile:strictnulls'
      displayName: 'Check regressions in files with strictNullChecks'

    - script: 'yarn compile:ci'
      displayName: 'Compile Assets'

    - script: 'yarn test-flaky'
      displayName: 'Run Tests'
      env:
        SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
        CI: true
        BROWSER_SOURCE_HARDWARE_ACCELERATION: 'OFF'
        SLOBS_TEST_STREAM_KEY: $(twitchStreamKey)

  - job: Screenshots

    pool:
      name: 'Default'

    workspace:
      clean: resources

    steps:

    - powershell: echo "IP for RDP connections:" $(Invoke-RestMethod ipinfo.io/ip)
      displayName: 'Get RDP address'

    - powershell: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      displayName: 'Setup Screen Resolution'

    - script: yarn install --frozen-lockfile --check-files
      displayName: 'Install Dependencies'

    - script: 'yarn screentest'
      displayName: 'Snapshot testing'
      env:
        CI: true
        BROWSER_SOURCE_HARDWARE_ACCELERATION: 'OFF'
        SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
        STREAMLABS_BOT_ID: $(streamlabsBotId)
        STREAMLABS_BOT_KEY: $(streamlabsBotKey)
        AWS_BUCKET: $(awsBucket)
        AWS_ACCESS_KEY: $(awsAccessKey)
        AWS_SECRET_KEY: $(awsSecretKey)

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'SnapshotsResults'
        targetPath: $(Build.SourcesDirectory)/test-dist/screentest
